//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main
{
    public partial class MasterPreview
    {
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;

        protected global::System.Web.UI.WebControls.Label lblMessage;

        protected global::System.Web.UI.WebControls.GridView gvEmployeeDetails;

        protected global::System.Web.UI.WebControls.GridView gvCompensationDetails;

        protected global::System.Web.UI.WebControls.GridView gvCurrentJob;

        protected global::System.Web.UI.WebControls.GridView gvPreviousEmployment;

        protected global::System.Web.UI.WebControls.GridView gvJobDetails;

        protected global::System.Web.UI.WebControls.GridView gvEducation;

        protected global::System.Web.UI.WebControls.GridView gvFamily;
    }
}
